name: trendmicro-container-security
description: Trend Micro Cloud One Container Security
appVersion: "0.0.4"
version: "0.0.4"
kubeVersion: ">=1.14.0-0"
apiVersion: v1
deprecated: false
home: https://github.com/trendmicro/cloudone-admission-controller-helm
maintainers:
  - name: Trend Micro
