# Default values for Trend Micro Cloud One - Admission Controller.
# This is a YAML-formatted file.

cloudOne:
  ## API key to be used with Trend Micro Cloud One Container Security
  ##
  ## Default value: (none)
  apiKey:

  ## endpoint is the url of Trend Micro Cloud One Container Security service
  ## Allows for full endpoint to be provided or the Cloud One region (ex: us-1).
  ##
  ## Default value: https://container.us-1.cloudone.trendmicro.com
  endpoint: https://container.us-1.cloudone.trendmicro.com

## extraLabels is a dictionary of additional labels that will be added to all resources
## created by this chart.
extraLabels: {}

## failurePolicy defines the bahaviour if an unreconized error or timeout occurs. Enabling
## this while not tagging kube-system to be ignored can easily cause the cluster to be
## unresponsive.
##
## Default value: Ignore
failurePolicy: Ignore

## enableKubeSystem will tell the admission controller to not ignore requests from the kube-system
## namespace.
##
## Default value: false
##
## WARNING: Enabling this could lead to your cluster to be unresponsive, depending on the set policy.
##          Only enable this with the greatest of care.
enableKubeSystem: false

## validationNamespaceSelector is a namespace selector defined so that matching namespaces will
## be subject to validation.
##
## For more information about namespace selectors, please see
## https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
## https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
validationNamespaceSelector:
  matchExpressions:
  - key: ignoreAdmissionControl
    operator: DoesNotExist

images:
  defaults:
    ## Default registry to pull images from. This can be overridden for
    ## each image by specifying the registry attribute at the image level.
    ## If no registry is provided, images will be pulled from your default
    ## registry (which may be Docker Hub).
    ##
    ## Default value: blank
    # registry:

    ## Default project / organization to pull images from. This can be
    ## overridden for each image by specifying the project attribute at the
    ## image level.
    ##
    ## Default value: trendmicrocloudone
    # project: trendmicrocloudone

    ## Default tag for images to pull. This can be overridden for each image
    ## by specifying the tag attribute at the image level.
    tag: 0.0.3

    ## Default pull policy for images. This can be overridden for each image
    ## by specifying the pullPolicy attribute at the image level.
    ##
    ## Default value: IfNotPresent
    pullPolicy: IfNotPresent

    ## Default secret for pulling images. This can be overridden for each
    ## image by specifying the imagePullSecret attribute at the image level.
    ##
    ## Default value: none
    # imagePullSecret:
  admissionController:
    repository: admission-controller
    digest: sha256:b50a2bcb0d5765765cd5aba12b7cba39a21308fab500a04aefa2f8d861fe49b0

replicas: {}

telemetry:
  ## enabled controls whether telemetry events will be sent.
  ##
  ## Default value: true
  enabled: true

  ## endpoint is the endpoint of the telemetry service.
  ##
  ## Default value: https://telemetry.deepsecurity.trendmicro.com
  endpoint: https://telemetry.deepsecurity.trendmicro.com

  ## interval controls the maximum interval between telemetry data reports
  ##
  ## Default value: 8h
  interval: 8h

  ## publicKey is the public key used when communicating with the telemetry service.
  ##
  ## Default value: (built-in)
  publicKey:

  ## apiKey is the API key used when communicating with the telemetry service.
  ##
  ## Default value: (built-in)
  apiKey:

certificate:
  ## commonName is the common name to use in the default signed certificate.
  ##
  ## Default value:
  commonName:

  ## ipAlternativeNames is a list of IP addresses to include as alternate names.
  ## in the default signed certificate.
  ##
  ## Default value: []
  ipAlternativeNames: []

  ## dnsAlternativeNames is a list of DNS names to include as alternate names
  ## in the default signed certificate.
  ##
  ## Default value: []
  dnsAlternativeNames: []

  ## lifetime is the lifetime in days of the default signed certificate.
  ##
  ## Default value: 3650
  lifetime: 3650

# securityContext specifies the security contexts that we'll apply to the pods.
securityContext:
  ## enabled is a global flag controlling whether security contexts are included at all in the manifest
  ## Default value: true
  enabled: true

  ## default is the default security context that we'll apply at the pod and container level.
  ## if `securityContext.enabled` is true, the `pod` value will be inserted into the `Deployment` manifest
  ## as part of the pod template and the `container` value will be inserted at the container level.
  default:
    pod:
      runAsNonRoot: true
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      # seLinuxOptions: "If unspecified, the container runtime will allocate a random SELinux context for each container": this seems appropriate.
      runAsUser: 1

resources:
  defaults: {}
    # If you want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

nodeSelector:
  defaults: {}

tolerations:
  defaults: []

affinity:
  defaults: {}
