# Default values for Trend Micro Cloud One - Container Security.
# This is a YAML-formatted file.

cloudOne:
  ## API key to be used with Trend Micro Cloud One Container Security
  ##
  ## Default value: (none)
  apiKey: 
    
  ## endpoint is the url of Trend Micro Cloud One Container Security service
  ## Allows for full endpoint to be provided or the Cloud One region (ex: us-1).
  ##
  ## Default value: https://container.us-1.cloudone.trendmicro.com
  endpoint: https://container.us-1.cloudone.trendmicro.com

  admissionController:
    enabled: true

    ## validationNamespaceSelector is a namespace selector defined so that matching namespaces will
    ## be subject to validation.
    ##
    ## For more information about namespace selectors, please see
    ## https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ## https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
    validationNamespaceSelector:
      matchExpressions:
      - key: ignoreAdmissionControl
        operator: DoesNotExist

    ## enableKubeSystem will tell the admission controller to not ignore requests from the kube-system
    ## namespace.
    ##
    ## Default value: false
    ##
    ## WARNING: Enabling this could lead to your cluster to be unresponsive, depending on the policy set.
    ##          Only enable this with the greatest of care.
    enableKubeSystem: false

    ## failurePolicy defines the bahaviour if an unreconized error or timeout occurs. Enabling
    ## this while not tagging kube-system to be ignored can easily cause the cluster to be
    ## unresponsive.
    ##
    ## Default value: Ignore
    failurePolicy: Ignore

    certificate:
      ## commonName is the common name to use in the default signed certificate.
      ##
      ## Default value:
      commonName:

      ## ipAlternativeNames is a list of IP addresses to include as alternate names.
      ## in the default signed certificate.
      ##
      ## Default value: []
      ipAlternativeNames: []

      ## dnsAlternativeNames is a list of DNS names to include as alternate names
      ## in the default signed certificate.
      ##
      ## Default value: []
      dnsAlternativeNames: []

      ## lifetime is the lifetime in days of the default signed certificate.
      ##
      ## Default value: 3650
      lifetime: 3650


  runtimeSecurity:
    enabled: false

    ## enableMasterNode will enable Runtime Security to run on master nodes as well
    ##
    ## Default value: false
    enableMasterNode: false

    ## API key to be used with Trend Micro Cloud One Runtime Security
    ##
    ## Default value: (none)
    apiKey:

    ## The API secret used to authenticate with Trend Micro Cloud One Runtime Security
    ##
    ## Default value: (none)
    secret:

    ## The helloURL for Trend Micro Cloud One Runtime Security
    ##
    ## Default value: https://agent-manager.app-protect.trendmicro.com
    helloURL: https://agent-manager.app-protect.trendmicro.com

    ## The level for Trend Micro Cloud One Runtime Security
    ##
    ## Default value: info
    logLevel: info

    ## The log location for Trend Micro Cloud One Runtime Security
    ##
    ## Default value: stdout
    logFile: stdout


  oversight:
    enabled: true

    ## enableKubeSystem will tell the Oversight controller to not ignore requests from the kube-system
    ## namespace.
    ##
    ## Default value: false
    ##
    ## WARNING: Enabling this could lead to your cluster to be unresponsive, depending on the policy set.
    ##          Only enable this with the greatest of care.
    enableKubeSystem: false
    
    ## syncPeriod is the time interval that how often Trend Micro Cloud One Container Security will evaluate 
    ## the running pods. 
    ##
    ## Default value: 3600s
    ## Minimum value: 600s
    ##
    syncPeriod: 3600s

    ## enableNetworkPolicyCreation will tell the Oversight controller to create the Kubernetes network policy if it doesn't exist.
    ## The created network policy is used to perform `isolate` mitigation. The created network policy will not get cleaned up automatically.
    ##
    ## Default value: true
    ##
    enableNetworkPolicyCreation: true

securityContextConstraints:
  # enable the Security Context Constraints creation in Openshift
  create: true

serviceAccount:
  ## enable the service account creation. Each component with specific permission will use individual service account.
  ## If set to false, the default service account will be used, which might not have sufficient permission and introduce the failure.
  ##
  ## Default value: true  
  create: true

  oversight:
    ## The name of the service account to use.
    ## If not set and create is true, a name is generated using the fullname of oversight template
    name: ""
    
    ## Annotations to add to the service account
    annotations: {}
  
  usage:
    ## The name of the service account to use.
    ## If not set and create is true, a name is generated using the fullname of oversight template
    name: ""
    
    ## Annotations to add to the service account
    annotations: {}

networkPolicy:
  ## enabled the network policy.
  ##
  ## Default value: true 
  enabled: true

telemetry:
  ## enabled controls whether telemetry events will be sent.
  ##
  ## Default value: true
  enabled: true

  ## endpoint is the endpoint of the telemetry service.
  ##
  ## Default value: https://telemetry.deepsecurity.trendmicro.com
  endpoint: https://telemetry.deepsecurity.trendmicro.com

  ## interval controls the maximum interval between telemetry data reports
  ##
  ## Default value: 8h
  interval: 8h

  ## publicKey is the public key used when communicating with the telemetry service.
  ##
  ## Default value: (built-in)
  publicKey:

  ## apiKey is the API key used when communicating with the telemetry service.
  ##
  ## Default value: (built-in)
  apiKey:

## securityContext specifies the security contexts that we'll apply to the pods.
##
## NOTE: securityContext does not apply to runtime security, since it requires special privileges
securityContext:
  ## enabled is a global flag controlling whether security contexts are included at all in the manifest
  ## Default value: true
  enabled: true

  ## default is the default security context that we'll apply at the pod and container level.
  ## if `securityContext.enabled` is true, the `pod` value will be inserted into the `Deployment` manifest
  ## as part of the pod template and the `container` value will be inserted at the container level.
  default:
    pod:
      runAsNonRoot: true
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      # seLinuxOptions: "If unspecified, the container runtime will allocate a random SELinux context for each container": this seems appropriate.
      runAsUser: 65532  # nonroot user

proxy:
  ## httpProxy, if set, will be used as the proxy for outbound HTTP traffic.
  ##
  ## The value may be either a complete URL or a `host[:port]`, in which
  ## case the `http` scheme is assumed.
  ##
  ## Default value: (none)
  httpProxy:

  ## httpsProxy, if set, will be used as the proxy for outbound HTTPS traffic. 
  ## If `httpsProxy` is not set, `httpProxy`
  ## is also checked and will be used if set.
  ##
  ## The value may be either a complete URL or a `host[:port]`, in which
  ## case the `http` scheme is assumed.
  ##
  ## Default value: (none)
  httpsProxy:

  ## noProxy, if set, is a list of hosts or `host:port` combinations which
  ## should not be accessed through the proxy.
  ##
  ## Default value: (none)
  noProxy: []

  ## username, if set, is the user name to provide to the outbound proxy when making requests.
  ##
  ## Default value: (none)
  username:

  ## password, if set, is the password to provide to the outbound proxy when making requests.
  ##
  ## Default value: (none)
  password:

resources:
  defaults: {}
  oversight: 
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 20Mi
  usage: 
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 20Mi

## NOTE: nodeSelector does not apply to runtime security
nodeSelector:
  defaults: {}

## NOTE: tolerations does not apply to runtime security
tolerations:
  defaults: []

## NOTE: affinity does not apply to runtime security
affinity:
  defaults: {}

## NOTE: replicas does not apply to runtime security
replicas: {}

## extraLabels is a dictionary of additional labels that will be added to all resources
## created by this chart.
extraLabels: {}

images:
  defaults:
    ## Default registry to pull images from. This can be overridden for
    ## each image by specifying the registry attribute at the image level.
    ## If no registry is provided, images will be pulled from your default
    ## registry (which may be Docker Hub).
    ##
    ## Default value: blank
    # registry:

    ## Default project / organization to pull images from. This can be
    ## overridden for each image by specifying the project attribute at the
    ## image level.
    ##
    ## Default value: trendmicrocloudone
    # project: trendmicrocloudone

    ## Default tag for images to pull. This can be overridden for each image
    ## by specifying the tag attribute at the image level.
    tag: 1.0.1

    ## Default pull policy for images. This can be overridden for each image
    ## by specifying the pullPolicy attribute at the image level.
    ##
    ## Default value: IfNotPresent
    pullPolicy: IfNotPresent

    ## Default secret for pulling images. This can be overridden for each
    ## image by specifying the imagePullSecret attribute at the image level.
    ##
    ## Default value: none
    # imagePullSecret:
  admissionController:
    repository: admission-controller
    digest: sha256:1441b475a7f6a3a91ec524a47ffc696a47f8c57783192aea9a2d00ce3891b44c

  runtimeSecurity:
    repository: runtime-protection
    digest: sha256:5e990570a9a20776c311058c6de5695ef42d7747f87a2389d78421825c0da1c0

  oversight:
    repository: oversight-controller
    digest: 

  usage:
    repository: usage-controller
    digest:
    
  rbacProxy:
    repository: rbac-proxy
    digest: 