apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "container.security.name" . }}-outbound-proxy
  labels:
    {{- include "container.security.labels" . | nindent 4 }}
data:
  httpProxy: {{ quote (default "" .Values.proxy.httpProxy) }}
  httpsProxy: {{ quote (default "" .Values.proxy.httpsProxy) }}
  noProxy: {{ (default (list) .Values.proxy.noProxy) | join "," | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "container.security.name" . }}-outbound-proxy-credentials
  labels:
    {{- include "container.security.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ default "" .Values.proxy.username | toString | b64enc | quote }}
  password: {{ default "" .Values.proxy.password | toString | b64enc | quote }}
