{{- if and .Values.securityContextConstraints.create (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: |
      This SCC provides the privilege requirement to run the Oversight-Controller in Openshift.
  name: {{ template "container.security.name" . }}-oversight
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container.security.labels" . | nindent 4 }} 
{{- $securityContextConstraints := .Values.serviceAccount.oversight.securityContextConstraints }}
{{ toYaml $securityContextConstraints }}
volumes:
- configMap
- downwardAPI
- emptyDir
- secret
users: 
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "oversight.serviceAccountName" . }}
{{- end }}
