{{- $cn := printf "%s.%s.svc" "trendmicro-admission-controller" .Release.Namespace }}
{{- $ca := genCA (printf "%s-ca" "trendmicro-admission-controller") (default 3650 (int .Values.certificate.lifetime)) -}}
{{- $cert := genSignedCert (default $cn .Values.certificate.commonName) (default nil .Values.certificate.ipAlternativeNames) (default (list $cn) .Values.certificate.dnsAlternativeNames) (default 3650 (int .Values.certificate.lifetime)) $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "admission.controller.fullname" . }}-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    service: trendmicro-admission-controller
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  key.pem: {{ $cert.Key | b64enc | quote }}
  cert.pem: {{ $cert.Cert | b64enc | quote }}

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "admission.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: trendmicro-admission-controller
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
webhooks:
  - name: {{ default $cn .Values.certificate.commonName }}
    namespaceSelector:
      matchExpressions:
      {{- range $k, $v := (required "A namespaceSelector is required" .Values.validationNamespaceSelector) }}
      {{- range $match := $v }}
      -
      {{- range $key, $op := $match }}
        {{ $key }}: {{ quote $op }}
      {{- end }}
      {{- end }}
      {{- end }}
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - '*'
        resources:
          - "pods"
          - "replicasets"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "jobs"
          - "cronjobs"
        scope: "Namespaced"
    failurePolicy: {{ required "A valid failure policy is required!" .Values.failurePolicy }}
    clientConfig:
      service:
        name: trendmicro-admission-controller
        namespace: {{ .Release.Namespace }}
        path: "/api/validate"
      caBundle: {{ $ca.Cert | b64enc | quote }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 30
